# Generated by Django 3.1.4 on 2020-12-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flaws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160)),
            ],
        ),
    ]
